import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NAVBAR_REM_HEIGHT } from "@/lib/global";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="standard">
      <body
        className={`${inter.className} w-screen flex flex-col items-center justify-center bg-base-100`}
      >
        <main className="w-full max-w-[1800px] bg-base-200">
          <Navbar />
          <div
            className="flex flex-col items-center"
            style={{
              minHeight: `calc(100vh - ${NAVBAR_REM_HEIGHT}rem)`,
            }}
          >
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
